openapi: 3.0.0
info:
  title: Global Accounts API
  description: API used to manage Organizations and Accounts for multiple products. Also responsible for authorization and authentication processes.
  version: 2.0.0
servers:
  - url: https://accounts.livechat.com/v2
    description: Main production server URL
paths:
  /clients:
    get:
      summary: List OAuth clients
      description: List all clients using `organization_id` obtained from the access token
      security:
        - oAuth2:
            - oauth_clients_manage
      tags:
        - Clients
    post:
      summary: Create OAuth client
      description: This method creates a new client for a given organization id
      security:
        - oAuth2:
            - oauth_clients_manage
            - dev_platform_admin
      tags:
        - Clients
  /clients/{client_id}:
    patch:
      summary: Update OAuth client
      description: This method updates a client for a given client id
      security:
        - oAuth2:
            - oauth_clients_manage
            - dev_platform_admin
      tags:
        - Clients
    delete:
      summary: Delete OAuth client
      description: This method removes an existing client and on successful call revoking all tokens related to the removed client
      security:
        - oAuth2:
            - oauth_clients_manage
      tags:
        - Clients
  /clients/{client_id}/scopes:
    put:
      summary: Update OAuth client scopes
      description: This method sets the scopes for a given client id. If the operation is successful, consents granted for an app are removed. Previously generated access tokens remains intact
      security:
        - oAuth2:
            - oauth_clients_manage
            - dev_platform_admin
      tags:
        - Clients
  /clients/{client_id}/consent:
    delete:
      summary: Revoke OAuth client consent
      description: This method removes consent for an existing client. Successful call revokes all tokens related to removed consent. The client will be no longer able to obtain any data from the account or organization
      security:
        - oAuth2:
            - oauth_clients_manage
            - ""
      tags:
        - Clients
  /accounts:
    get:
      summary: List all accounts
      description: Accounts are listed by using `organization_id` obtained from the access token
      security:
        - oAuth2:
            - accounts--all:ro
            - accounts--all:ro accounts.roles--all:ro
      tags:
        - Accounts
    post:
      tags:
        - Accounts
      summary: Creates new account
      description: Create an account for a given `organization_id`. This endpoint is idempotent. It's possible to set a password for a new account, but it should be done by reminding the password endpoint and custom postmark template
      security:
        - oAuth2:
            - accounts--all:rw
            - accounts--all:rw accounts.roles--all:rw
  /accounts/{account_id}:
    get:
      summary: Gets account
      description: Gets account by provided `id` or could be used by `me` for getting requester account
      security:
        - oAuth2:
            - accounts--my:ro
            - accounts--my:ro accounts.roles--all:ro
            - accounts--all:ro
            - accounts--all:ro accounts.roles--all:ro
      tags:
        - Accounts
    patch:
      tags:
        - Accounts
      summary: Updates account
      description: Updates account properties
      security:
        - oAuth2:
            - accounts--all:rw
            - accounts--all:rw accounts.roles--all:rw
    delete:
      tags:
        - Accounts
      summary: Delete account
      description: Deletes selected account
      security:
        - oAuth2:
            - accounts--my:rw
            - accounts--all:rw
  /v2/accounts/me/invitation_token:
    get:
      tags:
        - Accounts
      summary: Returns invitation token
      description: This method returns an active invite access token. This scope allows for creating unlimited accounts for a given organization. The token is not revoked after a successful call. The token can be safely attached to an invitation link or email. The token lifetime is limited to 14 days
      security:
        - oAuth2:
            - accounts--all:rw
    post:
      tags:
        - Accounts
      summary: Generate invitation token
      description: This method creates an invitation access token. Creating a new token revokes the previous one
      security:
        - oAuth2:
            - accounts--all:rw
  /v2/accounts/me/transfer_ownership:
    post:
      tags:
        - Accounts
      summary: Transfers ownership
      description: Adds the ability for the owner to transfer ownership to another account. After the operation, current owner becomes an administrator
      security:
        - oAuth2:
            - agents_transfer_ownership
  /accounts/{account_id}/roles:
    put:
      summary: Set account roles
      description: Set or delete the roles for a given `account_id`. Set overwrites a role group in case of conflicts. For example setting an administrator role for LiveChat will create or overwrite existing LiveChat role. Can't set or remove owner with this method
      security:
        - oAuth2:
            - accounts.roles--all:rw
      tags:
        - Accounts
  /organizations:
    get:
      tags:
        - Organizations
      summary: Get organizations
      description: Lists all organizations that the account belongs to, based on authorization
    post:
      tags:
        - Organizations
      summary: Create organization
      description: Create an organization and account. This endpoint does not send any emails. You can also use Bearer/Basic authorization then instead of creating a new account for an organization, and there will be created a new organization for an account associated with the token
  /organizations/{organization_id}:
    get:
      summary: Get organization
      description: Returns single organization by it's id, could use `my` for obtaining organization from authorization
      tags:
        - Organizations
    patch:
      tags:
        - Organizations
      summary: Update organization
      description: Updates organization properties
      security:
        - oAuth2:
            - organization--my:rw
  /personal_token:
    get:
      tags:
        - Personal Access
      summary: List Personal Tokens
      description: List all personal tokens for a given account.
      security:
        - oAuth2:
            - personal_access_manage
  /personal_token/info:
    get:
      tags:
        - Personal Access
      summary: Check if the personal token is valid.
      description: Check personal token provided in `Basic` auth.
  /v2/personal_token/{personal_token_id}:
    delete:
      summary: Delete personal token
      description: Invalidate and remove the personal token for provided id.
      tags:
        - Personal Access
      security:
        - oAuth2:
            - personal_access_manage
  /scopes:
    get:
      summary: Lists scopes
      description: List all available scopes
      security:
        - oAuth2:
            - dev_platform_admin
            - ""
      tags:
        - Scopes
  /accounts/{account_id}/password/resettable:
    post:
      summary: Check ability for reset password
      description: This method checks if a new password can be set using reset endpoint
      security:
        - oAuth2:
            - accounts.password--my:rw
            - accounts.password--all:rw
      tags:
        - Passwords
  /accounts/{account_id}/password/reset:
    post:
      summary: Set account password
      description: This method sets new password. Successful call revokes all session tokens
      security:
        - oAuth2:
            - accounts.password--my:rw
            - accounts.password--all:rw
      tags:
        - Passwords
  /roles:
    get:
      summary: List roles
      description: List roles for an organization
      security:
        - oAuth2:
            - accounts.roles--all:ro
      tags:
        - Roles
    post:
      summary: Create role
      description: Create custom role for an organization
      security:
        - oAuth2:
            - accounts.roles--all:rw
      tags:
        - Roles
  /roles/{role_id}:
    get:
      summary: Get role
      description: Get single role
      security:
        - oAuth2:
            - accounts.roles--all:rw
      tags:
        - Roles
    delete:
      summary: Delete role
      description: Delete single role
      security:
        - oAuth2:
            - accounts.roles--all:rw
      tags:
        - Roles
  /info:
    get:
      summary: Get token info
      tags:
        - Tokens
    delete:
      summary: Revoke an access token or refresh token. A refresh token is revoked with a related access token.
      tags:
        - Tokens
  /sessions:
    get:
      summary: List sessions
      description: This method returns all sessions for a given account id. The account id is obtained from an authorization grant
      security:
        - oAuth2:
            - sessions-my:ro
      tags:
        - Sessions
    delete:
      summary: Remove sessions
      description: Remove all sessions for a given account id. The account id is obtained from an authorization grant
      security:
        - oAuth2:
            - sessions-my:rw
      tags:
        - Sessions
  /sessions/{session_id}:
    get:
      summary: Get session
      description: Get a single session
      security:
        - oAuth2:
            - sessions-my:ro
      tags:
        - Sessions
    delete:
      summary: Remove session
      description: Remove specific session for a given account id. The account id is obtained from an authorization grant
      security:
        - oAuth2:
            - sessions-my:rw
      tags:
        - Sessions
  /sessions/tagged:
    get:
      summary: Check session tag
      description: Returns HTTP `200` when the account cookie exists (the cookie can be invalid)
      tags:
        - Sessions
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        implicit:
          authorizationUrl: https://accounts.livechat.com
          scopes:
            access_rules:ro: Read auto chat scopes configuration
            access_rules:rw: Add auto chat scopes configuration
            accounts--all:rc: Read or create an account
            accounts--all:ro: Read all accounts
            accounts--all:rw: Modify all accounts
            accounts--my:ro: Read my account
            accounts--my:rw: Modify my account
            accounts.roles--all:ro: Read all roles
            accounts.roles--all:rw: Modify all roles
            agents--all:ro: Read any agents profiles configuration
            agents--all:rw: Update any agents profiles configuration
            agents--my:ro: Read my profile configuration
            agents--my:rw: Update my profile configuration
            agents-bot--all:ro: Read any bot agents configuration
            agents-bot--all:rw: Delete and edit any bot agents configuration except status
            agents-bot--my:ro: Read my bot agents configuration
            agents-bot--my:rw: Add and update bot agents configuration
            agents_read: Read agents list
            agents_write: Manage agents list
            archives_read: Read chat archives
            archives_write: Add chat tags
            ban_customer: Ban customers
            banlist_read: Read banned customers list
            banlist_write: Manage banned customers
            billing--all:ro: Access to read all billing resources, invoices, account informations, subscriptions and in-app payments
            billing_manage: Offer in-app payments
            buttons_manage: Configure chat buttons
            canned_responses_read: Read canned responses list
            canned_responses_write: Add, update and delete canned responses
            chat_logos_manage: Change chat window logo
            chats--access:ro: Read chats with my access
            chats--access:rw: Update chats metadata in user access
            chats--all:ro: Read any chats
            chats--all:rw: Update any chats metadata
            chats--my:ro: Read my chats
            chats--my:rw: Update my chats metadata
            chats.conversation--access:rw: Update chats contents in user access
            chats.conversation--all:rw: Update any chats contents
            chats.conversation--my:rw: Update my chats contents
            customers.ban:rw: Ban customers
            customers:own: Manage customers identities
            customers:ro: Read customers
            customers:rw: Add and update customers
            domain_manage: Manage trusted domains
            eye_catcher_manage: Add, update and delete eye catchers
            forms_manage: Add, update and delete offline forms
            goals_read: Read goals list
            goals_write: Add, update and delete goals
            greetings_read: Read greetings list
            greetings_write: Add, update and delete greetings
            groups--all:ro: Read any groups
            groups--all:rw: Create, update and delete any groups
            groups--my:ro: Read my groups
            groups--my:rw: Create, update and delete my groups
            groups_read: Read groups list
            groups_write: Add, update and delete groups
            in_app_msg_manage: Read in-app messages
            integrations_read: Read integrations list
            languages_read: Read languages
            languages_write: Add, update and delete languages
            ledger_read: Read developers financial activity and balance
            multicast:rw: Multicast
            onboarding_manage: Manage onboarding
            organization--my:rw: Manage organization properties
            properties--all:ro: Read any properties configuration
            properties--my:ro: Read my properties configuration
            properties--my:rw: Add my properties configuration
            properties_manage: Manage license, group and agent properties
            properties_read: Read license, group and agent properties
            reports_read: Read reports
            routing_read: Read url rules list
            routing_write: Add, update and delete url rules
            sessions--my:ro: Read my sessions
            sessions--my:rw: Modify my sessions, signout
            surveys_manage: Add, update & delete chat surveys
            surveys_read: Read chat surveys
            tags_read: Read tags list
            tags_write: Add, update and delete tags
            tickets_manage: Update tickets settings
            tickets_read: Read tickets list
            tickets_write: Create and update tickets
            unban_customer: Remove customers from banned list
            visitors_read: Read visitors list
            webhooks--all:ro: Read any webhooks configuration
            webhooks--all:rw: Delete any webhooks configuration
            webhooks--my:ro: Read my webhooks configuration
            webhooks--my:rw: Add and delete my webhooks configuration
            webhooks_manage: Add, update and delete webhooks
            webhooks_write: Modify webhooks
