export { default as duration } from "./responses/chats/duration.json";
export { default as tags } from "./responses/chats/tags.json";
export { default as totalChats } from "./responses/chats/totalChats.json";
export { default as filters } from "./filters.json";
export { default as ranking } from "./responses/chats/ranking.json";
export { default as ratings } from "./responses/chats/ratings.json";
export { default as engagement } from "./responses/chats/engagement.json";
export { default as availability } from "./responses/agents/availability.json";
export { default as performance } from "./responses/agents/performance.json";
