#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

max_characters=37
branch_name="$(git rev-parse --abbrev-ref HEAD)"
branch_name_length=${#branch_name}

if [ $branch_name_length -gt $max_characters ];
then
  echo "Branch name can have maximum ${max_characters} characters but your has ${branch_name_length}"
  exit 1
fi

exit 0
