name: Deploy branch

on:
  push:
    branches:
      - master

jobs:
  deployer:
    name: "Deploy"
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Deploy changes
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify build --context production  && netlify deploy --prod --dir=.next
